QuanLyChuoiKhachSan/Areas/Admin/Controllers/KhachHangController.cs
using Model.Dao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanLyChuoiKhachSan.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: Admin/KhachHang
        public ActionResult Index(string searchString, int page = 1, int pageSize = 10)
        {
            var dao = new KhachHangDao();
            var model = dao.LayTatCaDS(searchString, page, pageSize);
            ViewBag.SearchString = searchString;
            return View(model);
        }

    }
}

QuanLyChuoiKhachSan/Areas/Admin/Views/KhachHang/Edit.cshtml
@model Model.EF.KhachHang
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Chỉnh Sữa
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaKhachHang)

        <div class="form-group">

            Tên Nhà Cung Cấp
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenKhachHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
            </div>
            
            SDT
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
            Giới Tính
            <div class="col-md-10">
                @Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
             Địa Chỉ
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>

            Email
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
           

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập Nhật" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về trang trước", "Index")
</div>

QuanLyChuoiKhachSan/Areas/Admin/Views/KhachHang/Index.cshtml
@model PagedList.IPagedList<Model.EF.KhachHang>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header{
    Danh Sách khách hàng
}


@using (Html.BeginForm("Index", "KhachHang", FormMethod.Get))
{
    <div class="row form-group">
        <div class="col-lg-12">
            <div class="col-md-4">
                <input type="text" value="@ViewBag.SearchString" class="form-control" placeholder="Mời nhập tên cần tìm" name="searchString" />
                <button type="submit" class="btn btn-success">Tìm kiếm</button>
            </div>
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            Mã Khách Hàng
        </th>
        <th>
            Tên Khách hàng
        </th>
        <th>
            Số điện thoại
        </th>
        <th>
            Giới tính
        </th>
        <th>
            Địa chỉ
        </th>
        <th>
            Email
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="row_@item.MaKhachHang">
            <td>
                @Html.DisplayFor(modelItem => item.TenKhachHang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Ajax.ActionLink("Xóa", "Delete", new { @id = item.MaKhachHang }, new AjaxOptions
              {
                  Confirm = "Bạn có muốn xóa quyền hạn này không.",
                  OnComplete = "$('#row_" + @item.MaKhachHang + "').remove()",
                  HttpMethod = "Delete"
              })
            </td>
        </tr>
    }

</table>
<label>
    Trang số: @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = @ViewBag.SearchString }))
</label>

QuanLyChuoiKhachSan/Areas/Admin/Views/KhachHang/ThemMoi.cshtml
@model Model.EF.KhachHang
@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@section header
    {
    Thêm Mới Khách Hàng
}
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            <div style="margin-left:10%">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    Tên Khách Hàng Mới:
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TenKhachHang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenKhachHang, "", new { @class = "text-danger" })
                    </div>
                    SDT:
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                    </div>
                    Giới Tính :
                    <div class="col-md-10">
                        <form>
                            <input name="gioitinh" type="radio" value="Nam" />Nam
                            <input name="gioitinh" type="radio" value="Nữ" />Nữ
                            <input name="gioitinh" type="radio" value="Khác" />Khác


                         @*@Html.EditorFor(model => model.GioiTinh, new { htmlAttributes = new { @class = "form-control" } })
                         @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })*@
                        </form>
                    </div>
                    Địa Chỉ:
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                    </div>
                    Email:
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                    </div>



                    <div class="form-group" style="text-align:center">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Tạo mới" class="btn btn-danger btn-icon-split" />
                        </div>
                    </div>
                </div>
        </div>
    }
</div>